import React    from 'react';
import ReactDOM from 'react-dom';

console.log('app running...');

ReactDOM.render(
    <div className="well">
        <h1>Generated by ReactJS</h1>
        <p>React JS is running...</p>
    </div>,
    document.getElementById('container')
);
